server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/want_lifu?useUnicode=true
    username: root
    password: 110412
  #邮箱配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mail:
  queue:
    name: local.mail.queue
  exchange:
    name: local.mail.exchange
  routing:
    key:
      name: local.mail.routing.key
msg:
  queue:
    name: local.msg.queue
  exchange:
    name: local.msg.exchange
  routing:
    key:
      name: local.msg.routing.key
elasticSearch:
  host: 127.0.0.1
  port: 9200
  client:
    connectNum: 10
    connectPerRoute: 50

#设置一个邮件发送人
want:
  mail:
    senderName: want-conpany


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
elasticsearch:
  host: 127.0.0.1
  port: 9300
  cluster:
    name: want-lifu
  pool: 5
jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer

